source 'https://rubygems.org'

gem 'bootstrap-sass',       '3.3.6.0'
gem 'rails', '4.2.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'
gem 'faker',                '~> 1.4.2'
gem 'will_paginate',           '~> 3.0.7'
gem 'bootstrap-will_paginate', '~> 0.0.10'
gem 'acts-as-taggable-on', '~> 3.4'
gem 'knock'
gem 'rack-cors', :require => 'rack/cors'
gem 'responders', '~> 2.0'
gem 'geocoder'
gem 'rabl'
gem 'oj'

group :development, :test do
  gem 'byebug'
  gem 'sqlite3'
  gem 'web-console', '~> 2.0'
  gem 'spring',      '1.1.3'
end

group :test do
  gem 'minitest-reporters', '1.0.5'
  gem 'mini_backtrace',     '0.1.3'
  gem 'guard-minitest',     '2.3.1'
end

group :production do
	gem 'pg'
	gem 'rails_12factor'
end
